# Generated by Django 5.1.2 on 2024-10-21 16:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shortener", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="url",
            old_name="clicks",
            new_name="hits",
        ),
    ]
